### ISSUE TITLE
The icm file should be not included¬¬

### ISSUE THREAD

**Issue by a97cck** [tourist-C/cms_transformer#1]
as title

**Comment by a97cck** [comment]
The ICC color profile of the svs can be obtained by :


The color profile can be extracted by GIMP
 > Extract: Open the image using GIMP 2.9, 
 > Click on "Image > Color Management > Save Color Profile to File".

or using 
ArgyllCMS ( https://www.argyllcms.com/ )
And it allow CLI and thus batch-able

**Comment by orange119120** [comment]
fixed in c7f3851333146eaa5ea0d5efc6064b8e25049078
